# Generated by Django 4.0 on 2022-01-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='msg',
            field=models.CharField(default='The category was created.', max_length=256),
        ),
    ]
