# Generated by Django 4.0 on 2022-01-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_article_category_alter_article_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='edited_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
