# Generated by Django 4.0 on 2022-01-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_category_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
