# Generated by Django 4.0 on 2022-01-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_history_alter_category_options_delete_articleold'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='msg',
            field=models.CharField(default='The article was created.', max_length=256),
        ),
    ]
